# Generated by Django 3.2 on 2021-04-14 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=250)),
                ('book_img', models.ImageField(upload_to='picture')),
                ('book_price', models.TextField()),
            ],
        ),
    ]
